Feature/default enum conversion
TNG/config-builder pull request #49
Opened 2020-11-20 18:55 UTC by krasched

automated string-to-enum-conversion, so that users no longer have to manually define TypeTransformers for any `Enum`, `List<Enum>` or `Set<Enum>` field

2020-11-22 16:11 UTC, hankem requested changes
Thanks for the PR for this useful feature!

I've left a few review comments for some further improvements.

2020-11-22 16:11 UTC, hankem commented on src/main/java/com/tngtech/configbuilder/util/GenericsAndCastingHelper.java
> +        Type collectionParameterType = ((ParameterizedType) field.getGenericType()).getActualTypeArguments()[0];
I wonder whether we should just apply `StringToEnumTypeTransformer` for every enum-valued type argument, i.e. replace this function with
```java
    public Collection<Class<? extends Enum<?>>> getEnumTypesRelevantFor(Field field) {
        if (field.getType().isEnum()) {
            return singletonList((Class<? extends Enum<?>>) field.getType());
        }
        if (field.getGenericType() instanceof ParameterizedType) {
            ParameterizedType parameterizedType = (ParameterizedType) field.getGenericType();
            return stream(parameterizedType.getActualTypeArguments())
                    .filter(type -> type instanceof Class && ((Class<?>) type).isEnum())
                    .map(enumType -> (Class<? extends Enum<?>>)enumType)
                    .collect(toList());
        }
        return emptyList();
    }
```
and use it in `FieldValueTransformer#initialize` in this way:
```java
        genericsAndCastingHelper.getEnumTypesRelevantFor(field)
                .forEach(enumClass -> availableTransformers.add(new StringToEnumTypeTransformer(enumClass)));
```
What do you think?

2020-11-28 08:54 UTC, krasched commented on src/main/java/com/tngtech/configbuilder/util/GenericsAndCastingHelper.java
> +    public <E extends Enum<E>> Optional<Class<E>> getEnumTypeOrParameterIfApplicable(Field field) {
Thanks, I changed it to package private.

2020-11-28 09:02 UTC, krasched commented on src/test/java/com/tngtech/configbuilder/util/FieldValueTransformerComponentTest.java
> +        assertThat(actualResult).isEqualTo(EnumSet.allOf(TestEnum.class));
Yes, your suggestion looks a bit more self-consistent.

2020-11-28 09:02 UTC, krasched commented on src/main/java/com/tngtech/configbuilder/annotation/typetransformer/TypeTransformer.java
> +    private Class<?> getTransformerSourceClass() {
Oh, yes. I reverted the change.

2020-11-28 09:02 UTC, krasched commented on src/main/java/com/tngtech/configbuilder/util/GenericsAndCastingHelper.java
> +        Type collectionParameterType = ((ParameterizedType) field.getGenericType()).getActualTypeArguments()[0];
Right, the more generic approach feels much more self-consistent. I even went one step further and included recursively any nested type parameter. If we already include cases that currently are not supported out of the box (e.g., maps) then there seems no reason to just restrict ourselves to non-nested parameterization.

2020-11-28 09:02 UTC, krasched commented on src/main/java/com/tngtech/configbuilder/util/GenericsAndCastingHelper.java
> +        Type collectionParameterType = ((ParameterizedType) field.getGenericType()).getActualTypeArguments()[0];
Uh, that's a bad fail, yes. I went now with a more generic approach as suggested by you below. I also extracted the functionality into its own class and added an extra test class for it.

2020-11-28 09:02 UTC, krasched commented on src/main/java/com/tngtech/configbuilder/util/GenericsAndCastingHelper.java
> +            return Optional.of((Class<E>) field.getType());
Right. I changed it.

2020-11-29 23:17 UTC, hankem approved these changes
Thanks for the update, LGTM!

Do you want to keep the individual commits? I'd personally just squash them into one.
(I guess I could just directly use github's `Rebase and merge` button, if you agree.)

2020-11-29 23:17 UTC, hankem commented on src/main/java/com/tngtech/configbuilder/util/EnumTypeExtractor.java
> +    }
Cool! 👍

2020-12-01 20:35 UTC, krasched commented
> Thanks for the update, LGTM!
> 
> Do you want to keep the individual commits? I'd personally just squash them into one.
> (I guess I could just directly use github's `Rebase and merge` button, if you agree.)

Please do as you like :-)

2020-12-02 05:38 UTC, merged